# Specify the programming language
language: node_js

# Specify the Node.js versions to test with
node_js:
  - "16"

# Cache dependencies to speed up builds
cache:
  npm: true
  directories:
    - node_modules

# Define the environment
env:
  global:
    - CI=true

# Install dependencies
install:
  - npm install

# Specify the build and test steps
script:
  # Run backend tests
  - npm run backend-test
  # Run frontend tests
  - npm run frontend-test
  # Build the frontend
  - npm run build-frontend

  # Notifications 
notifications:
  email:
    recipients:
      - bwaygdth@example.com
    on_success: always
    on_failure: always